### ISSUE TITLE
MFM Co Sample 

### ISSUE THREAD

**Issue by JanGieseler** [LISE-B26/PythonLab#1]
need to magnetize the Co film -> magnetometer, e.g. VSM, SQUID
Talk to Lara Tryputen (MIT, nanomagnets)

**Comment by JanGieseler** [comment]
need to magnetize the Co film -> magnetometer, e.g. VSM, SQUID
Talk to Lara Tryputen (MIT, nanomagnets)

**Comment by asafira** [comment]
Where did you save the data?

**Comment by JanGieseler** [comment]
It's still on the AFM network drive. However, we didn't see domains very clearly. Could have been because the MFM tip wasn't properly magnetized.
