### ISSUE TITLE
integration_time cannot be set to 0.05 in StanfordResearch_ESR without the daq crashing

### ISSUE THREAD

**Issue by asafira** [LISE-B26/PythonLab#11]
daq crashes if attempting to do an esr run with integration_time = 0.05.

**Comment by asafira** [comment]
Also, the same error comes up when setting a galvo scan to the currently highest integration time (time per point) of .01. The error regards the buffer to the daq not being large enough to store the data. 

I would be in favor of also adding one notch higher for integration time, as we have been using .01 a bunch and it's not inconceivable we might want it to be larger. Maybe .015 and .02 as well?

**Comment by akabcenell** [comment]
Changed daq DI acquisition from continuous to fixed point number, which allows it to create a buffer of the correct size
