### ISSUE TITLE
findmax should choose the NV found that is closest to the original point (in case if finds more than 1 NV)

### ISSUE THREAD

**Issue by asafira** [LISE-B26/PythonLab#31]
Currently, findmax finds the NV that is first in the list of found nvs, and it should instead find the one closest to the original point.

**Comment by akabcenell** [comment]
Also have it reduce mass and retry if it fails the first time

**Comment by akabcenell** [comment]
Added all of the above requested functionality, mass reduction done by min_mass_adjustment function and may need to be empirically adjusted
