### ISSUE TITLE
Find_Max_NV plot in ESR_Selected_NVs only updates at end of scan, not during

### ISSUE THREAD

**Issue by akabcenell** [LISE-B26/PythonLab#36]

**Comment by JanGieseler** [comment]
problem is that signals from doubly nested script don't propagate correctly
=> write dummy script to test this

**Comment by JanGieseler** [comment]
signal propagation does work. The issue is with not correctly implementing the _plot and _update_plot functions

one way this might be solved is to check in _plot of the superscript if _plot of subscript was successful and if not set refresh_plot to True to enforce a call of _plot until succesful
