### ISSUE TITLE
PulseDelays not being seen as a QThread and then is wrapped by gui

### ISSUE THREAD

**Issue by akabcenell** [LISE-B26/PythonLab#38]
This causes the script to crash. If checked from within PulseDelays, it thinks that it is a QThread. Will likely affect all other scripts inheriting from ExecutePulseBlasterSequence

**Comment by akabcenell** [comment]
Confirmed to be an issue from all scripts that inherit from ExecutePulseBlasterSequence. @JanGieseler working on removing all QThread dependencies, which should cause this issue to no longer occur.

**Comment by JanGieseler** [comment]
Since Scripts are no longer QThreads, this issue should be resolved
